name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Swift 6.0.0
      run: |
        git clone https://github.com/kylef/swiftenv.git ~/.swiftenv
        echo 'export SWIFTENV_ROOT="$HOME/.swiftenv"' >> $HOME/.bash_profile
        echo 'export PATH="$SWIFTENV_ROOT/bin:$PATH"' >> $HOME/.bash_profile
        echo 'eval "$(swiftenv init -)"' >> $HOME/.bash_profile
        source $HOME/.bash_profile
        swiftenv install 6.0.0
        swiftenv global 6.0.0
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
    - name: First interaction
      uses: actions/first-interaction@v1.3.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
          👋 Welcome! Thanks for opening your first issue. We appreciate your contribution!
          Please make sure to review our contributing guidelines.
        pr-message: |
          🚀 Welcome aboard! Thanks for submitting your first pull request.
          A maintainer will review it shortly. In the meantime, feel free to check out our documentation.
    - name: Cache SwiftPM build
      uses: actions/cache@v4
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
