name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test -v
      - name: Cache SwiftPM build
        uses: actions/cache@v4
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

  first-interaction:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/first-interaction@v1.3.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            👋 Welcome! Thanks for opening your first issue. We appreciate your contribution!
            Please make sure to review our contributing guidelines.
          pr-message: |
            🚀 Welcome aboard! Thanks for submitting your first pull request.
            A maintainer will review it shortly. In the meantime, feel free to check out our documentation.
